<?xml version='1.0'?>
<robot xmlns:xacro ="http://www.ros.org/wiki/xacro"  name="robot">

    <xacro:include filename="inertial_macros.xacro"/>
	<xacro:include filename="gazebo_auto_control.xacro"/>
	


	<xacro:property name="chassis_length" value="1.778" />
	<xacro:property name="chassis_width" value="1.27" />
	<xacro:property name="chassis_height" value="0.05" />
	<xacro:property name="chassis_mass" value="12" />
	<xacro:property name="wheel_radius" value="0.381" />
	<xacro:property name="wheel_height" value="0.254" />	
	<xacro:property name="wheel_mass" value="4" />

    <!--dummy link-->
	<link name="base_link"/>


	<joint name="joint-base-chassis" type="fixed">
		<parent link="base_link"/>
		<child link="chassis-link"/>
		<origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
	</joint>
	
	<!--chassis link-->
	<link name="chassis-link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size="${chassis_length} ${chassis_width} ${chassis_height}" />
			</geometry>
			<material name="brown">
				<color rgba="0.3 0 0.4 1"/>
			</material>		
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size="${chassis_length} ${chassis_width} ${chassis_height}" />
			</geometry>
		</collision> 
		<!-- <inertial>
			<mass value="0.4" />
			<inertia ixx="0.00048333" iyy="0.0013367" izz="0.0018133"
			ixy="0" ixz="0" iyz="0"/>
		</inertial> -->

        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="0 0.0 0" rpy="0 0 0"/>
        </xacro:inertial_box>

	</link>
	
	<joint name="joint-base-chassis" type="fixed">
		<parent link="base_link"/>
		<child link="chassis-link"/>
		<origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
	</joint>

	<gazebo reference="chassis-link">
        <material>Gazebo/Brown</material>
    </gazebo>


	<joint name="joint-chassis-upper-chassis" type="fixed">
		<parent link="chassis-link"/>
		<child link="upper-chassis-link"/>
		<origin xyz="0 0 1.03632" rpy="0 0 0" />
	</joint>


	<link name="upper-chassis-link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size="${chassis_length} ${chassis_width} ${chassis_height}" />
			</geometry>
			<material name="brown">
				<color rgba="0.3 0 0.4 1"/>
			</material>		
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size="${chassis_length} ${chassis_width} ${chassis_height}" />
			</geometry>
		</collision> 
		<!-- <inertial>
			<mass value="0.4" />
			<inertia ixx="0.00048333" iyy="0.0013367" izz="0.0018133"
			ixy="0" ixz="0" iyz="0"/>
		</inertial> -->

        <!-- <xacro:inertial_box mass="3" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="0 0.0 0" rpy="0 0 0"/>
        </xacro:inertial_box> -->

	</link>
	
	

	<gazebo reference="upper-chassis-link">
        <material>Gazebo/Brown</material>
    </gazebo>


    <material name="blue">
		<color rgba="0 0.4 0.5 1"/>
	</material>

	<material name="black">
		<color rgba="0 0 0 1"/>
	</material>

	<material name="white">
		<color rgba="1 1 1 1"/>
	</material>


	<xacro:macro name="stand" params="x_position y_position x_reflect y_reflect">
	<!-- ${x_position}-${y_position}-wheel-link -->

		<joint name="joint-chassis-${x_position}-${y_position}-stand" type="fixed">
			<parent link="chassis-link"/>
			<child link="${x_position}-${y_position}-stand-link"/>
			<origin xyz="${x_reflect*0.3*chassis_length} ${y_reflect*(chassis_width/3+wheel_height/2)} ${(wheel_height*2)+0.04}" rpy="0 0 0" />
			<axis xyz="0 0 1" />
		</joint>

		<link name="${x_position}-${y_position}-stand-link">
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<cylinder radius ="0.05"  length="1.03632" />
				</geometry>
				<material name="blue" />
			</visual>
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<cylinder radius ="0.05"  length="1.03632" />
				</geometry>
			</collision>

            <!-- <xacro:inertial_cylinder mass="1" length="1.03632" radius="0.05">
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            </xacro:inertial_cylinder> -->

		</link>
		
	</xacro:macro>

	<xacro:stand x_position="front" y_position="right" x_reflect="1" y_reflect="1" />
	<xacro:stand x_position="front" y_position="left" x_reflect="1" y_reflect="-1" />
	<xacro:stand x_position="rear" y_position="right" x_reflect="-1" y_reflect="1" />
	<xacro:stand x_position="rear" y_position="left" x_reflect="-1" y_reflect="-1" />

	<gazebo reference="front-right-stand-link">
        <material>Gazebo/Blue</material>
    </gazebo>
	<gazebo reference="front-left-stand-link">
        <material>Gazebo/Blue</material>
    </gazebo>
	<gazebo reference="rear-right-stand-link">
        <material>Gazebo/Blue</material>
    </gazebo>
	<gazebo reference="rear-left-stand-link">
        <material>Gazebo/Blue</material>
    </gazebo>

	<!--LEFT SIDE-->

	<joint name="front_left_wheel_joint" type="continuous">
        <parent link="chassis-link"/>
        <child link="front_left_wheel"/>
        <axis xyz="0 0 1"/>
        <origin xyz="${(1)*0.3*chassis_length} ${(-1)*(chassis_width/2+wheel_height/2)} 0" rpy="-${pi/2} 0 0"/>
    </joint>

    <link name="front_left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_height}"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_height}" radius="${wheel_radius}">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_cylinder>
        
    </link>



	<joint name="rear_left_wheel_joint" type="continuous">
        <parent link="chassis-link"/>
        <child link="rear_left_wheel"/>
        <axis xyz="0 0 1"/>
        <origin xyz="${(-1)*0.3*chassis_length} ${(-1)*(chassis_width/2+wheel_height/2)} 0" rpy="-${pi/2} 0 0"/>
    </joint>

    <link name="rear_left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_height}"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_height}" radius="${wheel_radius}">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_cylinder>
        
    </link>


	<!--RIGHT SIDE-->

	<joint name="front_right_wheel_joint" type="continuous">
        <parent link="chassis-link"/>
        <child link="front_right_wheel"/>
        <axis xyz="0 0 -1"/>
        <origin xyz="${(1)*0.3*chassis_length} ${(1)*(chassis_width/2+wheel_height/2)} 0" rpy="${pi/2} 0 0"/>
    </joint>

    <link name="front_right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_height}"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_height}" radius="${wheel_radius}">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_cylinder>
        
    </link>

	<joint name="rear_right_wheel_joint" type="continuous">
        <parent link="chassis-link"/>
        <child link="rear_right_wheel"/>
        <axis xyz="0 0 -1"/>
        <origin xyz="${(-1)*0.3*chassis_length} ${(1)*(chassis_width/2+wheel_height/2)} 0" rpy="${pi/2} 0 0"/>
    </joint>

    <link name="rear_right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>

        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_height}"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_height}" radius="${wheel_radius}">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_cylinder>
        
    </link>






	<gazebo reference="front_right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>
	<gazebo reference="front_left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>
	<gazebo reference="rear_right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>
	<gazebo reference="rear_left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

	<joint name="joint-chassis-lidar-stand" type="fixed">
			<parent link="upper-chassis-link"/>
			<child link="chassis-lidar-stand-link"/>
			<origin xyz="0 0 ${0.4318/2}" rpy="0 0 0" />
			<axis xyz="0 0 1" />
	</joint>


	<link name="chassis-lidar-stand-link">
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<box size="0.1 0.1 0.4318" />
					
				</geometry>
				<material name="white" />
			</visual>
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<box size="0.1 0.1 0.4318" />
				</geometry>
			</collision>

            <!-- <xacro:inertial_cylinder mass="1" length="0.4318" radius="0.03">
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            </xacro:inertial_cylinder> -->

	</link>
	

	<gazebo reference="chassis-lidar-stand-link">
        <material>Gazebo/White</material>
    </gazebo>


	<joint name="joint-chassis-lidar" type="fixed">
		<parent link="chassis-lidar-stand-link"/>
		<child link="lidar_link"/>
		<origin xyz="0 0 ${0.4318/2}" rpy="0 0 0" />
	</joint>


    <link name="lidar_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<cylinder radius="0.2" length="0.10" />
			</geometry>
			<material name="black">
				<color rgba="0 0 0 1"/>
			</material>		
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<cylinder radius="0.2" length="0.10" />
			</geometry>
		</collision>

	</link>
	
	

	<gazebo reference="lidar-ink">
        <material>Gazebo/Black</material>
    </gazebo>


    <!-- <link name="camera_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<cylinder radius="0.15" length="0.07" />
			</geometry>
			<material name="black">
				<color rgba="0 0 0 1"/>
			</material>		
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<cylinder radius="0.15" length="0.07" />
			</geometry>
		</collision>

	</link>
	
	<joint name="joint-chassis-camera" type="fixed">
		<parent link="chassis-link"/>
		<child link="camera_link"/>
		<origin xyz="0.508 0.254 0.45" rpy="0 0 0" />
	</joint> -->


</robot>